name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build

      - name: Build distribution
        run: ./gradlew :server:distZip

      - uses: actions/upload-artifact@v6
        with:
          name: galkon-dist
          path: server/build/distributions/server.zip
